export const STOCK_LOADING = "STOCK_LOADING";
export const STOCK_SUCCESS = "STOCK_SUCCESS";
export const STOCK_FAILURE = "STOCK_FAILURE";

export const TRADE_LOADING = "TRADE_LOADING";
export const TRADE_SUCCESS = "TRADE_SUCCESS";
export const TRADE_FAILURE = "TRADE_FAILURE";

export const STOCK_OWN_LOADING = "STOCK_OWN_LOADING";
export const STOCK_OWN_SUCCESS = "STOCK_OWN_SUCCESS";
export const STOCK_OWN_FAILURE = "STOCK_OWN_FAILURE";
